using System.Globalization;
using System.Text;
using Caca.Binding;
using Caca.Diagnostics;
using Caca.Syntax;

namespace Caca.Emit;

/// <summary>
/// Compiles a type-checked program to a single, self-contained C file.
/// </summary>
/// <remarks>
/// The third backend. It exists so a program can run where no .NET runtime
/// can go — compiled by any C compiler, including a freestanding one for a
/// kernel booted straight from GRUB. Generated code touches the world only
/// through the <c>caca_</c> runtime functions emitted at the top of the file,
/// so swapping the hosted runtime for a freestanding one changes nothing
/// below it. It must agree with the other two backends on every program;
/// the parity tests compile its output and hold it to that.
/// </remarks>
public sealed class CEmitter
{
    private readonly StringBuilder _text = new();
    private readonly IReadOnlyDictionary<string, FunctionSymbol> _functions;
    private readonly bool _freestanding;
    private int _indent;
    private int _loopNumber;

    /// <summary>The C code that a <c>continue</c> or <c>break</c> must become, innermost loop last.</summary>
    private readonly Stack<(string Break, string Continue)> _loops = new();

    private CEmitter(IReadOnlyDictionary<string, FunctionSymbol> functions, bool freestanding)
    {
        _functions = functions;
        _freestanding = freestanding;
    }

    /// <summary>
    /// Renders <paramref name="unit"/> as C, or reports why it cannot be.
    /// </summary>
    /// <param name="freestanding">
    /// True to embed the runtime that needs no operating system, for a
    /// program booted directly; false for the hosted one, built with a plain
    /// C compiler.
    /// </param>
    /// <returns>The diagnostics; the program text is only valid when there are none.</returns>
    public static IReadOnlyList<Diagnostic> Emit(
        CompilationUnit unit,
        IReadOnlyDictionary<string, FunctionSymbol> functions,
        out string program,
        bool freestanding = false)
    {
        var diagnostics = new DiagnosticBag();

        // Extern functions are .NET methods; there is no .NET where this
        // output runs. Rejected here rather than in the type checker because
        // the same program is still fine for the other two backends.
        foreach (var function in functions.Values)
        {
            if (function.IsExtern)
            {
                diagnostics.Report(
                    DiagnosticCode.ExternNotAvailableInC,
                    function.NameLocation,
                    $"'{function.Name}' is bound to a .NET method, which a program compiled to C cannot call");
            }
        }

        if (diagnostics.HasErrors)
        {
            program = string.Empty;
            return [.. diagnostics];
        }

        var emitter = new CEmitter(functions, freestanding);
        emitter.EmitProgram(unit);
        program = emitter._text.ToString();
        return [];
    }

    private void EmitProgram(CompilationUnit unit)
    {
        _text.AppendLine(_freestanding
            ? "/* Generated by the cacalang compiler, freestanding. Link with boot/boot.s; see boot/README.md. */"
            : "/* Generated by the cacalang compiler. Build with: cc <this file> -o <name> */");
        _text.AppendLine();
        _text.Append((_freestanding ? CRuntime.Freestanding : CRuntime.Hosted).ReplaceLineEndings("\n"));
        _text.AppendLine();

        // Every function is declared before any is defined, so a call can
        // reference a function declared later in the file, or its own.
        foreach (var function in _functions.Values)
        {
            _text.Append("static ").Append(Signature(function)).AppendLine(";");
        }

        _text.AppendLine();

        foreach (var function in _functions.Values)
        {
            _text.Append("static ").AppendLine(Signature(function));
            EmitBody(function.Declaration.Body, function.Declaration);
            _text.AppendLine();
        }

        _text.AppendLine("int main(void)");
        EmitBody(unit.TopLevel, declaration: null);
        return;

        string Signature(FunctionSymbol function)
        {
            var parameters = function.Parameters.Count == 0
                ? "void"
                : string.Join(", ", function.Parameters.Select(p => $"{CType(p.Type)} {Variable(p.Name)}"));

            return $"{CType(function.ReturnType)} {Function(function.Name)}({parameters})";
        }
    }

    /// <summary>
    /// Emits a function body, or the top level, as one C block.
    /// </summary>
    /// <remarks>
    /// The language has one flat scope per function: a variable declared
    /// inside a loop is visible after it. C scopes to the block, so every
    /// local is hoisted to the top of the function and a declaration in the
    /// body becomes a plain assignment. The type checker has already proved
    /// nothing is read before it is written.
    /// </remarks>
    private void EmitBody(BlockStatement body, FunctionDeclaration? declaration)
    {
        Line("{");
        _indent++;

        // Only main needs this, and only in the hosted runtime: it puts
        // stdio into binary mode, which matters only on Windows and only
        // before anything is written or read.
        if (declaration is null && !_freestanding)
        {
            Line("caca_init_io();");
        }

        var locals = new List<(string Name, CacaType Type)>();
        CollectLocals(body, locals);

        foreach (var (name, type) in locals)
        {
            Line($"{CType(type)} {Variable(name)};");
        }

        if (locals.Count > 0)
        {
            _text.AppendLine();
        }

        EmitStatements(body);

        if (declaration is null)
        {
            Line("return 0;");
        }
        else if (declaration.ReturnType is not null)
        {
            // The type checker proved this line unreachable; it exists so the
            // C compiler sees a value on every path too.
            Line($"return {Default(CacaTypeExtensions.Parse(declaration.ReturnType.Name) ?? CacaType.Int)};");
        }

        _indent--;
        Line("}");
        return;

        static string Default(CacaType type) => type switch
        {
            CacaType.Float => "0.0",
            CacaType.String => "(caca_str){ 0, \"\" }",
            CacaType.Bool => "false",
            _ => "0",
        };
    }

    /// <summary>Finds every variable a body declares, in declaration order.</summary>
    private static void CollectLocals(Statement statement, List<(string Name, CacaType Type)> locals)
    {
        switch (statement)
        {
            case BlockStatement block:
                foreach (var child in block.Statements)
                {
                    CollectLocals(child, locals);
                }

                break;

            case VariableDeclaration declaration:
                // The declared type wins over the initializer's, and an
                // initializer widened to float makes the variable a float.
                var type = declaration.DeclaredType?.Type
                    ?? declaration.Initializer.EffectiveType;
                locals.Add((declaration.Name, type));
                break;

            case ForStatement loop:
                if (loop.DeclaresVariable)
                {
                    locals.Add((loop.Name, CacaType.Int));
                }

                CollectLocals(loop.Body, locals);
                break;

            case IfStatement conditional:
                CollectLocals(conditional.ThenBranch, locals);

                if (conditional.ElseBranch is not null)
                {
                    CollectLocals(conditional.ElseBranch, locals);
                }

                break;

            case WhileStatement loop:
                CollectLocals(loop.Body, locals);
                break;
        }
    }

    private void EmitStatements(BlockStatement block)
    {
        foreach (var statement in block.Statements)
        {
            EmitStatement(statement);
        }
    }

    private void EmitStatement(Statement statement)
    {
        switch (statement)
        {
            case BlockStatement block:
                EmitStatements(block);
                break;

            case VariableDeclaration declaration:
                Line($"{Variable(declaration.Name)} = {Emit(declaration.Initializer)};");
                break;

            case AssignmentStatement assignment:
                Line($"{Variable(assignment.Name)} = {Emit(assignment.Value)};");
                break;

            case PrintStatement print:
                Line($"{PrintFunction(print.Expression.EffectiveType)}({Emit(print.Expression)});");
                break;

            case ReadStatement read:
                Line($"{Variable(read.Name)} = {ReadFunction(read.Type)}();");
                break;

            case IfStatement conditional:
                EmitIf(conditional);
                break;

            case WhileStatement loop:
                Line($"while {EmitCondition(loop.Condition)}");
                Line("{");
                _indent++;

                // C's while has this loop's exact shape, so its own break and
                // continue mean the right thing inside it.
                _loops.Push(("break;", "continue;"));
                EmitStatement(loop.Body);
                _loops.Pop();

                _indent--;
                Line("}");
                break;

            case ForStatement loop:
                EmitFor(loop);
                break;

            case ReturnStatement returned:
                Line(returned.Value is null ? "return;" : $"return {Emit(returned.Value)};");
                break;

            case CallStatement call:
                // A discarded value is discarded explicitly, so a C compiler
                // asked to warn about ignored results stays quiet.
                Line(call.Call.Type == CacaType.Void
                    ? $"{Emit(call.Call)};"
                    : $"(void){Emit(call.Call)};");
                break;

            case BreakStatement:
                Line(_loops.Peek().Break);
                break;

            case ContinueStatement:
                Line(_loops.Peek().Continue);
                break;

            default:
                throw new ArgumentOutOfRangeException(
                    nameof(statement), statement, $"unhandled statement {statement.GetType().Name}");
        }
    }

    private void EmitIf(IfStatement conditional)
    {
        Line($"if {EmitCondition(conditional.Condition)}");
        Line("{");
        _indent++;
        EmitStatement(conditional.ThenBranch);
        _indent--;
        Line("}");

        if (conditional.ElseBranch is null)
        {
            return;
        }

        Line("else");
        Line("{");
        _indent++;
        EmitStatement(conditional.ElseBranch);
        _indent--;
        Line("}");
    }

    /// <summary>
    /// Emits a <c>for</c> loop with the language's semantics: both bounds
    /// inclusive, the upper bound evaluated once, the body free to reassign
    /// the loop variable, and no wrap-around when the bound is the largest
    /// int — the bound is tested before the increment, exactly as the IL
    /// backend orders it.
    /// </summary>
    /// <remarks>
    /// C's <c>for</c> cannot express test-before-increment, so the loop is an
    /// endless one with the test in its tail. A <c>continue</c> must reach
    /// that tail rather than the top, which C's <c>continue</c> would do, so
    /// it becomes a <c>goto</c> to a label just before the test.
    /// </remarks>
    private void EmitFor(ForStatement loop)
    {
        var number = ++_loopNumber;
        var bound = $"caca_bound_{number}";
        var tail = $"caca_next_{number}";
        var counter = Variable(loop.Name);

        Line("{");
        _indent++;
        Line($"{counter} = {Emit(loop.From)};");
        Line($"int32_t {bound} = {Emit(loop.To)};");
        Line($"if ({counter} <= {bound})");
        Line("{");
        _indent++;
        Line("for (;;)");
        Line("{");
        _indent++;

        _loops.Push(("break;", $"goto {tail};"));
        EmitStatement(loop.Body);
        _loops.Pop();

        // The label is only written when a continue jumps to it, or the C
        // compiler warns about it going unused.
        if (UsesContinue(loop.Body, depth: 0))
        {
            _indent--;
            Line($"{tail}:;");
            _indent++;
        }

        Line($"if ({counter} >= {bound}) break;");
        Line($"{counter} = caca_add({counter}, 1);");
        _indent--;
        Line("}");
        _indent--;
        Line("}");
        _indent--;
        Line("}");
    }

    /// <summary>Whether a statement contains a <c>continue</c> belonging to the loop around it.</summary>
    private static bool UsesContinue(Statement statement, int depth) => statement switch
    {
        ContinueStatement => depth == 0,
        BlockStatement block => block.Statements.Any(s => UsesContinue(s, depth)),
        IfStatement conditional => UsesContinue(conditional.ThenBranch, depth)
            || (conditional.ElseBranch is not null && UsesContinue(conditional.ElseBranch, depth)),

        // A continue inside a nested loop belongs to that loop.
        WhileStatement or ForStatement => false,
        _ => false,
    };

    // ---------------------------------------------------------- expressions

    /// <summary>
    /// Renders an expression, applying the widening the type checker decided
    /// on — the one place an int becomes a float, as in the other backends.
    /// </summary>
    private string Emit(Expression expression)
    {
        var text = EmitCore(expression);

        return expression.ConvertedTo == CacaType.Float && expression.Type == CacaType.Int
            ? $"(double){text}"
            : text;
    }

    /// <summary>
    /// Renders a condition wrapped in exactly one pair of parentheses, for
    /// <c>if</c> and <c>while</c>.
    /// </summary>
    /// <remarks>
    /// Every binary expression already parenthesizes itself, on purpose:
    /// nothing here works out real operator precedence, so an expression
    /// re-embedded in a larger one needs its own grouping every time. Adding
    /// this condition's parentheses on top of that, unconditionally, would
    /// double them for the common case of a bare comparison — <c>if (n == 0)</c>
    /// becoming <c>if ((n == 0))</c> — which is valid C, but is exactly the
    /// shape <c>-Wparentheses-equality</c> warns about, reading as a typo for
    /// assignment.
    /// </remarks>
    private string EmitCondition(Expression condition)
    {
        var text = Emit(condition);
        return IsFullyParenthesized(text) ? text : $"({text})";
    }

    /// <summary>Whether an expression's rendered text is already exactly one parenthesized group.</summary>
    private static bool IsFullyParenthesized(string text)
    {
        if (text.Length < 2 || text[0] != '(' || text[^1] != ')')
        {
            return false;
        }

        var depth = 0;

        for (var i = 0; i < text.Length; i++)
        {
            if (text[i] == '(')
            {
                depth++;
            }
            else if (text[i] == ')' && --depth == 0)
            {
                // The opening paren closed before the end of the text, as in
                // "(a)+(b)": two groups, not one wrapping the whole thing.
                return i == text.Length - 1;
            }
        }

        return false;
    }

    private string EmitCore(Expression expression) => expression switch
    {
        LiteralExpression literal => Literal(literal),
        VariableExpression variable => Variable(variable.Name),
        ParenthesizedExpression parenthesized => Emit(parenthesized.Expression),
        UnaryExpression unary => Unary(unary),
        BinaryExpression binary => Binary(binary),
        CallExpression call => $"{Function(call.Name)}({string.Join(", ", call.Arguments.Select(Emit))})",
        _ => throw new ArgumentOutOfRangeException(
            nameof(expression), expression, $"unhandled expression {expression.GetType().Name}"),
    };

    private static string Literal(LiteralExpression literal) => literal.LiteralType switch
    {
        CacaType.Int => literal.IntValue.ToString(CultureInfo.InvariantCulture),
        CacaType.Bool => literal.BoolValue ? "true" : "false",
        CacaType.Float => FloatLiteral(literal.FloatValue),
        _ => StringLiteral(literal.StringValue),
    };

    /// <summary>A double literal C reads back as exactly the same value.</summary>
    private static string FloatLiteral(double value)
    {
        // Shortest round-trip text; a C compiler parses it back to the same
        // bits, because both sides round correctly.
        var text = value.ToString(CultureInfo.InvariantCulture);
        return text.Contains('.') || text.Contains('E') || text.Contains('e') ? text : text + ".0";
    }

    /// <summary>A string as a length and C literal pair, bytes preserved exactly.</summary>
    private static string StringLiteral(string value)
    {
        var bytes = Encoding.UTF8.GetBytes(value);
        var escaped = new StringBuilder();

        foreach (var b in bytes)
        {
            // Three-digit octal escapes cannot run into the character after
            // them, which hex escapes can.
            escaped.Append(b switch
            {
                (byte)'"' => "\\\"",
                (byte)'\\' => "\\\\",
                >= 0x20 and < 0x7f => ((char)b).ToString(),
                _ => $"\\{Convert.ToString(b, 8).PadLeft(3, '0')}",
            });
        }

        return $"(caca_str){{ {bytes.Length}, \"{escaped}\" }}";
    }

    private string Unary(UnaryExpression unary)
    {
        var operand = Emit(unary.Operand);

        return unary.Operator switch
        {
            UnaryOperator.Identity => operand,
            UnaryOperator.Not => $"(!{operand})",
            _ when unary.Type == CacaType.Float => $"(-{operand})",

            // Negating int.MinValue must wrap, and signed negation in C may not.
            _ => $"caca_neg({operand})",
        };
    }

    private string Binary(BinaryExpression binary)
    {
        // Concatenation converts the non-string operand to text, matching the
        // interpreter's Stringify and the IL backend's EmitAsString.
        if (binary.Operator == BinaryOperator.Add && binary.Type == CacaType.String)
        {
            return $"caca_concat({AsText(binary.Left)}, {AsText(binary.Right)})";
        }

        var left = Emit(binary.Left);
        var right = Emit(binary.Right);

        if (binary.Operator is BinaryOperator.Equal or BinaryOperator.NotEqual
            && binary.Left.EffectiveType == CacaType.String)
        {
            var equal = $"caca_str_eq({left}, {right})";
            return binary.Operator == BinaryOperator.Equal ? equal : $"(!{equal})";
        }

        // Int arithmetic wraps, which C's signed operators do not promise;
        // int division and remainder check for zero. Floats use the C
        // operators directly: IEEE 754 is IEEE 754 in every backend.
        var ints = binary.Left.EffectiveType == CacaType.Int && binary.Right.EffectiveType == CacaType.Int;

        return binary.Operator switch
        {
            BinaryOperator.Add when ints => $"caca_add({left}, {right})",
            BinaryOperator.Subtract when ints => $"caca_sub({left}, {right})",
            BinaryOperator.Multiply when ints => $"caca_mul({left}, {right})",
            BinaryOperator.Divide when ints => $"caca_div({left}, {right})",
            BinaryOperator.Modulo when ints => $"caca_rem({left}, {right})",
            BinaryOperator.Modulo => $"fmod({left}, {right})",
            BinaryOperator.Add => $"({left} + {right})",
            BinaryOperator.Subtract => $"({left} - {right})",
            BinaryOperator.Multiply => $"({left} * {right})",
            BinaryOperator.Divide => $"({left} / {right})",
            BinaryOperator.Equal => $"({left} == {right})",
            BinaryOperator.NotEqual => $"({left} != {right})",
            BinaryOperator.Less => $"({left} < {right})",
            BinaryOperator.LessOrEqual => $"({left} <= {right})",
            BinaryOperator.Greater => $"({left} > {right})",
            BinaryOperator.GreaterOrEqual => $"({left} >= {right})",

            // C's && and || already evaluate their right side only when the
            // left has not settled the answer.
            BinaryOperator.LogicalAnd => $"({left} && {right})",
            BinaryOperator.LogicalOr => $"({left} || {right})",
            _ => throw new ArgumentOutOfRangeException(nameof(binary), binary.Operator, "unhandled binary operator"),
        };
    }

    /// <summary>Renders an expression as text, the way concatenation needs it.</summary>
    private string AsText(Expression expression) => expression.EffectiveType switch
    {
        CacaType.String => Emit(expression),
        CacaType.Int => $"caca_int_text({Emit(expression)})",
        CacaType.Bool => $"caca_bool_text({Emit(expression)})",
        _ => $"caca_double_text({Emit(expression)})",
    };

    // -------------------------------------------------------------- helpers

    private static string CType(CacaType type) => type switch
    {
        CacaType.Int => "int32_t",
        CacaType.Float => "double",
        CacaType.Bool => "bool",
        CacaType.String => "caca_str",
        CacaType.Void => "void",
        _ => throw new InvalidOperationException("the error type has no C representation"),
    };

    private static string PrintFunction(CacaType type) => type switch
    {
        CacaType.Int => "caca_print_int",
        CacaType.Float => "caca_print_double",
        CacaType.Bool => "caca_print_bool",
        _ => "caca_print_str",
    };

    private static string ReadFunction(CacaType type) => type switch
    {
        CacaType.Int => "caca_read_int",
        CacaType.Float => "caca_read_double",
        _ => "caca_read_str",
    };

    /// <summary>
    /// A user name as a C identifier. The prefixes keep user names, however
    /// they are spelled, away from C's keywords and the runtime's names.
    /// </summary>
    private static string Variable(string name) => "v_" + name;

    private static string Function(string name) => "fn_" + name;

    private void Line(string text) =>
        _text.Append(' ', _indent * 4).AppendLine(text);
}
