using Avalonia.Controls;
using Avalonia.Interactivity;

namespace AIL_Studio_Avalonia.Views
{
    /// <summary>Simple Yes/No modal, used for the unsaved-changes discard confirmation
    /// (ported from AIL-Studio/MainForm.cs's MessageBox.Show(..., YesNo)).</summary>
    public partial class ConfirmDialog : Window
    {
        // InitializeComponent() is generated by Avalonia's build-time IL weaving — must not
        // be hand-declared (see MainWindow.axaml.cs for why).
        public ConfirmDialog() => InitializeComponent();

        public ConfirmDialog(string message) : this()
        {
            MessageText.Text = message;
        }

        private void OnYesClick(object? sender, RoutedEventArgs e) => Close(true);

        private void OnNoClick(object? sender, RoutedEventArgs e) => Close(false);
    }
}
