using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;

namespace AIL_Studio_Avalonia.Views
{
    /// <summary>Modal prompt for VM stdin reads (KEI 0x01, AL = 0x03/0x04). Ported from
    /// AIL-Studio/StudioConsole.cs's ShowInputDialog.</summary>
    public partial class InputDialog : Window
    {
        // Parameterless constructor required by the XAML loader; not used directly.
        // InitializeComponent() is generated by Avalonia's build-time IL weaving — must not
        // be hand-declared (see MainWindow.axaml.cs for why).
        public InputDialog() => InitializeComponent();

        public InputDialog(string prompt) : this()
        {
            PromptText.Text = prompt;
            InputBox.KeyDown += (_, e) =>
            {
                if (e.Key == Key.Enter) Accept();
            };
        }

        private void OnOkClick(object? sender, RoutedEventArgs e) => Accept();

        private void Accept() => Close(InputBox.Text ?? string.Empty);
    }
}
