using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using Avalonia.Media;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using AvaloniaEdit.Indentation;
using Artemis_IL;
using AIL_Studio.Compiler;

namespace AIL_Studio_Avalonia.Views
{
    /// <summary>
    /// Main IDE window. Ported (MVP scope — editor, compile, run; the step debugger stays
    /// WinForms-only for now) from AIL-Studio/MainForm.cs. Code-behind style, matching the
    /// original: no ViewModel layer, event handlers drive everything directly.
    /// </summary>
    public partial class MainWindow : Window
    {
        private static readonly IBrush BOutputInfo = new SolidColorBrush(Color.Parse("#9CDCFE"));
        private static readonly IBrush BOutputSuccess = new SolidColorBrush(Color.Parse("#6A9955"));
        private static readonly IBrush BOutputError = new SolidColorBrush(Color.Parse("#F44747"));

        private static readonly FilePickerFileType AilSourceFileType = new("AIL Source")
        {
            Patterns = new[] { "*.ail", "*.asm" }
        };

        private string? _filePath;
        private bool _modified;
        private Window? _consoleDockWindow;
        private bool _closeConfirmed;

        public MainWindow()
        {
            // InitializeComponent() is generated by Avalonia's build-time IL weaving
            // (Avalonia.Build.Tasks) — it must NOT be hand-declared. The generated version
            // does both AvaloniaXamlLoader.Load(this) AND named-field (x:Name) wiring in one
            // step; a hand-written override that only does the former pre-empts the real
            // one, so every named field (Editor, OutputText, ...) silently stays null forever.
            InitializeComponent();

            AddHandler(KeyDownEvent, OnWindowKeyDown, RoutingStrategies.Tunnel);
            Closing += OnWindowClosing;
            // TextArea (and its own TextView, a further-nested templated part of
            // TextEditor's control template) only exist once the template actually applies —
            // TemplateApplied is the precise signal for that.
            Editor.TemplateApplied += OnEditorTemplateApplied;
        }

        private void OnEditorTemplateApplied(object? sender, Avalonia.Controls.Primitives.TemplateAppliedEventArgs e)
        {
            Editor.TemplateApplied -= OnEditorTemplateApplied;

            Editor.TextArea.TextView.LineTransformers.Add(new AilSyntaxColorizer());
            Editor.TextArea.IndentationStrategy = new DefaultIndentationStrategy();
            Editor.TextArea.Caret.PositionChanged += (_, _) => UpdateStatusPosition();

            Editor.Text = LoadEmbeddedExample("calculator.ail");
            _modified = false;
            UpdateTitle();
        }

        // ── Keyboard shortcuts ──────────────────────────────────────────────────
        // MenuItem.InputGesture is display-only in Avalonia (same as WinForms'
        // ShortcutKeyDisplayString) — actual handling goes through this tunnel handler,
        // mirroring MainForm.cs's ProcessCmdKey override.

        private async void OnWindowKeyDown(object? sender, KeyEventArgs e)
        {
            bool ctrl = e.KeyModifiers.HasFlag(KeyModifiers.Control) || e.KeyModifiers.HasFlag(KeyModifiers.Meta);
            switch (e.Key)
            {
                case Key.N when ctrl: await New(); e.Handled = true; break;
                case Key.O when ctrl: await Open(); e.Handled = true; break;
                case Key.S when ctrl: await Save(); e.Handled = true; break;
                case Key.F5: Compile(); e.Handled = true; break;
                case Key.F6: CompileAndRun(); e.Handled = true; break;
            }
        }

        // ── File menu ────────────────────────────────────────────────────────────

        private async void OnNewClick(object? sender, RoutedEventArgs e) => await New();
        private async void OnOpenClick(object? sender, RoutedEventArgs e) => await Open();
        private async void OnSaveClick(object? sender, RoutedEventArgs e) => await Save();
        private async void OnSaveAsClick(object? sender, RoutedEventArgs e) => await SaveAs();
        private void OnExitClick(object? sender, RoutedEventArgs e) => Close();

        private void OnLoadExampleHelloWorldClick(object? sender, RoutedEventArgs e) =>
            _ = LoadExample("hello_world_db.ail");

        private void OnLoadExampleCalculatorClick(object? sender, RoutedEventArgs e) =>
            _ = LoadExample("calculator.ail");

        private async Task New()
        {
            if (!await ConfirmDiscardIfModified()) return;
            Editor.Text = string.Empty;
            _filePath = null;
            _modified = false;
            UpdateTitle();
        }

        private async Task Open()
        {
            if (!await ConfirmDiscardIfModified()) return;

            var files = await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions
            {
                Title = "Open AIL Source",
                AllowMultiple = false,
                FileTypeFilter = new[] { AilSourceFileType, FilePickerFileTypes.All }
            });
            if (files.Count == 0) return;

            await using var stream = await files[0].OpenReadAsync();
            using var reader = new StreamReader(stream);
            Editor.Text = await reader.ReadToEndAsync();
            _filePath = files[0].TryGetLocalPath();
            _modified = false;
            UpdateTitle();
        }

        private async Task Save()
        {
            if (_filePath == null) { await SaveAs(); return; }
            await File.WriteAllTextAsync(_filePath, Editor.Text);
            _modified = false;
            UpdateTitle();
        }

        private async Task SaveAs()
        {
            var file = await StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions
            {
                Title = "Save AIL Source",
                DefaultExtension = "ail",
                SuggestedFileName = _filePath is null ? "untitled.ail" : Path.GetFileName(_filePath),
                FileTypeChoices = new[]
                {
                    new FilePickerFileType("AIL Source") { Patterns = new[] { "*.ail" } },
                    new FilePickerFileType("Assembly") { Patterns = new[] { "*.asm" } },
                    FilePickerFileTypes.All
                }
            });
            if (file is null) return;

            string? path = file.TryGetLocalPath();
            if (path is null) return;

            await File.WriteAllTextAsync(path, Editor.Text);
            _filePath = path;
            _modified = false;
            UpdateTitle();
        }

        private async Task LoadExample(string resourceName)
        {
            if (!await ConfirmDiscardIfModified()) return;
            Editor.Text = LoadEmbeddedExample(resourceName);
            _filePath = null;
            _modified = false;
            UpdateTitle();
        }

        private static string LoadEmbeddedExample(string resourceName)
        {
            var asm = Assembly.GetExecutingAssembly();
            using var stream = asm.GetManifestResourceStream(resourceName)
                ?? throw new InvalidOperationException($"Embedded example '{resourceName}' not found.");
            using var reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }

        // ── Edit menu ────────────────────────────────────────────────────────────

        private void OnUndoClick(object? sender, RoutedEventArgs e) => Editor.Undo();
        private void OnRedoClick(object? sender, RoutedEventArgs e) => Editor.Redo();
        private void OnCutClick(object? sender, RoutedEventArgs e) => Editor.Cut();
        private void OnCopyClick(object? sender, RoutedEventArgs e) => Editor.Copy();
        private void OnPasteClick(object? sender, RoutedEventArgs e) => Editor.Paste();
        private void OnSelectAllClick(object? sender, RoutedEventArgs e) => Editor.SelectAll();

        // ── Build menu ───────────────────────────────────────────────────────────

        private void OnCompileClick(object? sender, RoutedEventArgs e) => Compile();
        private void OnCompileAndRunClick(object? sender, RoutedEventArgs e) => CompileAndRun();

        private byte[]? Compile()
        {
            ClearOutput();
            AppendOutput("── Compiling… ──\n", BOutputInfo);
            try
            {
                var compiler = new Compiler(Editor.Text);
                byte[] bytecode = compiler.Compile();
                AppendOutput(
                    $"✓ Compiled — {bytecode.Length / 6} instruction(s), {bytecode.Length} byte(s).\n",
                    BOutputSuccess);
                return bytecode;
            }
            catch (BuildException ex)
            {
                AppendOutput($"✗ Error on line {ex.SrcLineNumber}: {ex.Message}\n", BOutputError);
                return null;
            }
            catch (Exception ex)
            {
                AppendOutput($"✗ {ex.Message}\n", BOutputError);
                return null;
            }
        }

        private void CompileAndRun()
        {
            byte[]? bytecode = Compile();
            if (bytecode is null) return;

            AppendOutput("── VM output ──\n", BOutputInfo);
            RunAsync(bytecode);
        }

        private void RunAsync(byte[] code)
        {
            Globals.console = new AvaloniaStudioConsole(AppendOutput, this);
            Globals.DebugMode = false;

            Task.Run(() =>
            {
                try
                {
                    Executable.Run(code);
                    AppendOutput("\n── Done ─────────────────────────────\n", BOutputInfo);
                }
                catch (Exception ex)
                {
                    AppendOutput($"\n✗ Runtime error: {ex.Message}\n", BOutputError);
                }
            });
        }

        // ── Help menu ────────────────────────────────────────────────────────────

        private async void OnAboutClick(object? sender, RoutedEventArgs e)
        {
            var dlg = new Window
            {
                Title = "About AIL Studio",
                Width = 340,
                Height = 160,
                CanResize = false,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                Background = (IBrush)this.FindResource("BrushSidebar")!,
                Content = new TextBlock
                {
                    Text = "AIL Studio (Avalonia)\n\n" +
                           "Cross-platform IDE for the Artemis Intermediate Language.\n" +
                           $"Avalonia {typeof(Avalonia.Application).Assembly.GetName().Version}",
                    Margin = new Avalonia.Thickness(16),
                    Foreground = (IBrush)this.FindResource("BrushDefaultText")!,
                    TextWrapping = Avalonia.Media.TextWrapping.Wrap
                }
            };
            await dlg.ShowDialog(this);
        }

        // ── Output panel ─────────────────────────────────────────────────────────

        private void ClearOutput()
        {
            if (!Dispatcher.UIThread.CheckAccess())
            {
                Dispatcher.UIThread.Post(ClearOutput);
                return;
            }
            OutputText.Inlines?.Clear();
        }

        private void AppendOutput(string text, IBrush? brush)
        {
            if (!Dispatcher.UIThread.CheckAccess())
            {
                Dispatcher.UIThread.Post(() => AppendOutput(text, brush));
                return;
            }
            OutputText.Inlines ??= new Avalonia.Controls.Documents.InlineCollection();
            var run = new Avalonia.Controls.Documents.Run(text);
            if (brush != null) run.Foreground = brush;
            OutputText.Inlines.Add(run);
            OutputScroll.ScrollToEnd();
        }

        // ── Undockable console ───────────────────────────────────────────────────

        private void OnUndockClick(object? sender, RoutedEventArgs e)
        {
            if (_consoleDockWindow != null)
            {
                _consoleDockWindow.Close();
                return;
            }
            UndockConsole();
        }

        private void UndockConsole()
        {
            var original = SplitGrid.RowDefinitions[2];
            SplitGrid.Children.Remove(OutputContainer);
            SplitGrid.RowDefinitions[2] = new RowDefinition(new Avalonia.Controls.GridLength(0));
            Splitter.IsVisible = false;

            var popped = new Window
            {
                Title = "AIL Studio — Output",
                Width = 520,
                Height = 320,
                Content = OutputContainer,
                Background = (IBrush)this.FindResource("BrushSidebar")!
            };
            popped.Position = new Avalonia.PixelPoint(
                (int)(Position.X + Width) + 8, (int)Position.Y);
            popped.Closing += (_, _) => RedockConsole();
            _consoleDockWindow = popped;
            popped.Show();

            UndockButton.Content = "⊞";
            ToolTip.SetTip(UndockButton, "Dock back into main window…");

            _ = original; // original row size restored explicitly (2*) in RedockConsole
        }

        private void RedockConsole()
        {
            if (_consoleDockWindow is null) return;
            var popped = _consoleDockWindow;
            _consoleDockWindow = null;

            popped.Content = null;
            SplitGrid.RowDefinitions[2] = new RowDefinition(new Avalonia.Controls.GridLength(2, Avalonia.Controls.GridUnitType.Star));
            SplitGrid.Children.Add(OutputContainer);
            Grid.SetRow(OutputContainer, 2);
            Splitter.IsVisible = true;

            UndockButton.Content = "⊡";
            ToolTip.SetTip(UndockButton, "Pop out console…");
        }

        // ── Title / status / modified tracking ──────────────────────────────────

        private void OnEditorTextChanged(object? sender, EventArgs e)
        {
            _modified = true;
            UpdateTitle();
        }

        private void UpdateTitle()
        {
            string name = _filePath is null ? "Untitled" : Path.GetFileName(_filePath);
            Title = $"{(_modified ? "● " : string.Empty)}{name} — AIL Studio";
            StatusFile.Text = _filePath ?? "New file";
        }

        private void UpdateStatusPosition()
        {
            var caret = Editor.TextArea.Caret;
            StatusPos.Text = $"Ln {caret.Line}, Col {caret.Column}";
        }

        private async Task<bool> ConfirmDiscardIfModified()
        {
            if (!_modified) return true;
            var dlg = new ConfirmDialog("You have unsaved changes. Discard them?");
            return await dlg.ShowDialog<bool>(this);
        }

        private async void OnWindowClosing(object? sender, WindowClosingEventArgs e)
        {
            if (_closeConfirmed || !_modified) return;
            e.Cancel = true;

            bool discard = await ConfirmDiscardIfModified();
            if (discard)
            {
                _closeConfirmed = true;
                Close();
            }
        }
    }
}
