<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Caca.Cli</RootNamespace>
    <AssemblyName>caca</AssemblyName>
    <Description>Command line driver for the Good for Nothing compiler.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Caca.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Caca.Compiler\Caca.Compiler.csproj" />
    <ProjectReference Include="..\Caca.CilBackend\Caca.CilBackend.csproj" />
  </ItemGroup>

</Project>
